from __future__ import annotations

import base64
from collections.abc import Iterable
from dataclasses import dataclass
from typing import Any

import numpy as np


@dataclass(frozen=True)
class PlotlyAxisMap:
    """Mapping from Plotly axis IDs to a matplotlib subplot position."""

    axis_id: str
    row: int
    col: int


def plotly_to_matplotlib(
    fig: Any,
    *,
    figsize: tuple[float, float] | None = None,
    dpi: int = 100,
    include_colorbar: bool = True,
    showlegend: bool | None = None,
    tight_layout: bool = True,
):
    """
    Convert a Plotly figure into a matplotlib figure.

    This converter rebuilds the plot from Plotly's trace and layout data. It is
    intended for static export workflows where Plotly + Kaleido is inconvenient,
    such as remote servers without an available browser.

    Supported trace types are scatter, histogram, heatmap, and bar. These cover
    the traces generated by ``marimo_lib.util.plot.go_*`` helpers.

    Parameters
    ----------
    fig :
        Plotly ``go.Figure`` or a dict-like object with ``data`` and ``layout``.
    figsize :
        Matplotlib figure size in inches. If omitted, Plotly layout width and
        height are used when available.
    dpi :
        Matplotlib figure DPI.
    include_colorbar :
        Add colorbars for heatmaps and color-mapped scatter traces.
    showlegend :
        Force legend visibility. If omitted, Plotly ``layout.showlegend`` is
        used.
    tight_layout :
        Call ``matplotlib.figure.Figure.tight_layout`` before returning.

    Returns
    -------
    tuple
        ``(matplotlib_figure, axes)`` where axes is a 2D numpy array.
    """
    plt, _ = _import_matplotlib()
    figure_dict = _as_plotly_dict(fig)
    data = figure_dict.get("data", [])
    layout = figure_dict.get("layout", {})

    subplot_info = _get_subplot_info(layout, data)
    nrows = subplot_info["nrows"]
    ncols = subplot_info["ncols"]

    if figsize is None:
        figsize = _get_figsize(layout, dpi=dpi, nrows=nrows, ncols=ncols)

    mpl_fig, axes = plt.subplots(
        nrows,
        ncols,
        squeeze=False,
        figsize=figsize,
        dpi=dpi,
    )

    _apply_figure_layout(mpl_fig, layout)
    _apply_axes_layout(axes, subplot_info, layout)

    for trace in data:
        trace = _to_plain_dict(trace)
        ax = _get_axis_for_trace(axes, subplot_info, trace)
        _draw_trace(
            ax,
            trace,
            include_colorbar=include_colorbar,
            mpl_fig=mpl_fig,
        )

    _apply_legends(axes, layout, showlegend)
    _hide_empty_axes(axes)

    if tight_layout:
        mpl_fig.tight_layout()

    return mpl_fig, axes


def figure_to_matplotlib(fig: Any, **kwargs: Any):
    """Alias for ``plotly_to_matplotlib``."""
    return plotly_to_matplotlib(fig, **kwargs)


def plot_plotly_as_matplotlib(
    fig: Any,
    *,
    show: bool = True,
    return_axes: bool = False,
    **kwargs: Any,
):
    """
    Convert a Plotly figure to matplotlib and display it in a notebook.

    This is a notebook-friendly wrapper around ``plotly_to_matplotlib``. It
    returns the matplotlib figure by default, so a marimo or Jupyter notebook can
    render the result directly. Set ``return_axes=True`` when you want to keep
    editing the converted axes.

    Examples
    --------
    ``plot_plotly_as_matplotlib(fig)``

    ``mpl_fig, axes = plot_plotly_as_matplotlib(fig, return_axes=True)``
    """
    plt, _ = _import_matplotlib()
    mpl_fig, axes = plotly_to_matplotlib(fig, **kwargs)
    if show:
        plt.show()
    if return_axes:
        return mpl_fig, axes
    return mpl_fig


def show_plotly_as_matplotlib(fig: Any, **kwargs: Any):
    """Alias for ``plot_plotly_as_matplotlib``."""
    return plot_plotly_as_matplotlib(fig, **kwargs)


def save_plotly_as_matplotlib(
    fig: Any,
    path: str,
    *,
    format: str | None = None,
    close: bool = False,
    **kwargs: Any,
) -> str:
    """
    Convert a Plotly figure to matplotlib and save it.

    Examples
    --------
    ``save_plotly_as_matplotlib(fig, "figure.pdf")``

    ``save_plotly_as_matplotlib(fig, "figure.png", dpi=200)``
    """
    plt, _ = _import_matplotlib()
    mpl_fig, _ = plotly_to_matplotlib(fig, **kwargs)
    mpl_fig.savefig(path, format=format)
    if close:
        plt.close(mpl_fig)
    return path


def _import_matplotlib():
    try:
        import matplotlib.pyplot as plt
        from matplotlib.colors import LinearSegmentedColormap
    except ImportError as exc:
        raise ImportError(
            "plotly_matplotlib requires matplotlib. "
            "Install it with `pip install matplotlib` or `uv add matplotlib`."
        ) from exc

    return plt, LinearSegmentedColormap


def _as_plotly_dict(fig: Any) -> dict[str, Any]:
    if hasattr(fig, "to_plotly_json"):
        return fig.to_plotly_json()
    if isinstance(fig, dict):
        return fig
    raise TypeError("fig must be a Plotly Figure or a dict with data/layout")


def _to_plain_dict(obj: Any) -> dict[str, Any]:
    if isinstance(obj, dict):
        return obj
    if hasattr(obj, "to_plotly_json"):
        return obj.to_plotly_json()
    return dict(obj)


def _get_subplot_info(
    layout: dict[str, Any],
    data: list[dict[str, Any]],
) -> dict[str, Any]:
    xaxes = _collect_layout_axes(layout, axis="x")
    yaxes = _collect_layout_axes(layout, axis="y")

    if not xaxes:
        xaxes = {"x": {"domain": [0.0, 1.0]}}
    if not yaxes:
        yaxes = {"y": {"domain": [0.0, 1.0]}}

    x_domains = _unique_domains([axis["domain"] for axis in xaxes.values()])
    y_domains = _unique_domains([axis["domain"] for axis in yaxes.values()])
    x_domains.sort(key=_domain_center)
    y_domains.sort(key=_domain_center, reverse=True)

    x_to_col = {
        axis_id: _domain_index(axis_info["domain"], x_domains)
        for axis_id, axis_info in xaxes.items()
    }
    y_to_row = {
        axis_id: _domain_index(axis_info["domain"], y_domains)
        for axis_id, axis_info in yaxes.items()
    }

    trace_axes = {}
    for trace in data:
        trace = _to_plain_dict(trace)
        xaxis = trace.get("xaxis", "x")
        yaxis = trace.get("yaxis", "y")
        if xaxis not in x_to_col:
            x_to_col[xaxis] = 0
        if yaxis not in y_to_row:
            y_to_row[yaxis] = 0
        trace_axes[(xaxis, yaxis)] = (
            y_to_row.get(yaxis, 0),
            x_to_col.get(xaxis, 0),
        )

    return {
        "nrows": max(1, len(y_domains)),
        "ncols": max(1, len(x_domains)),
        "xaxes": xaxes,
        "yaxes": yaxes,
        "x_to_col": x_to_col,
        "y_to_row": y_to_row,
        "trace_axes": trace_axes,
    }


def _collect_layout_axes(
    layout: dict[str, Any],
    *,
    axis: str,
) -> dict[str, dict[str, Any]]:
    axes = {}
    prefix = f"{axis}axis"
    default_id = axis

    for key, value in layout.items():
        if key == prefix or (key.startswith(prefix) and key[len(prefix):].isdigit()):
            axis_id = default_id if key == prefix else f"{axis}{key[len(prefix):]}"
            value = _to_plain_dict(value)
            axes[axis_id] = {
                **value,
                "domain": list(value.get("domain", [0.0, 1.0])),
            }

    return axes


def _unique_domains(domains: list[list[float]], *, tol: float = 1e-9):
    unique = []
    for domain in domains:
        if not any(np.allclose(domain, known, atol=tol) for known in unique):
            unique.append(domain)
    return unique


def _domain_center(domain: list[float]) -> float:
    return float(domain[0] + domain[1]) / 2.0


def _domain_index(domain: list[float], domains: list[list[float]]) -> int:
    centers = [_domain_center(d) for d in domains]
    center = _domain_center(domain)
    return int(np.argmin([abs(center - known) for known in centers]))


def _get_figsize(
    layout: dict[str, Any],
    *,
    dpi: int,
    nrows: int,
    ncols: int,
) -> tuple[float, float]:
    width = layout.get("width")
    height = layout.get("height")
    if width is not None and height is not None:
        return (float(width) / dpi, float(height) / dpi)
    return (5.0 * ncols, 3.8 * nrows)


def _apply_figure_layout(mpl_fig: Any, layout: dict[str, Any]) -> None:
    title = _get_title_text(layout.get("title"))
    if title:
        mpl_fig.suptitle(title)


def _apply_axes_layout(
    axes: np.ndarray,
    subplot_info: dict[str, Any],
    layout: dict[str, Any],
) -> None:
    annotations = layout.get("annotations", [])
    for axis_id, axis_info in subplot_info["xaxes"].items():
        col = subplot_info["x_to_col"].get(axis_id, 0)
        row = _row_for_xaxis(subplot_info, axis_id)
        ax = axes[row, col]
        title = _get_title_text(axis_info.get("title"))
        if title:
            ax.set_xlabel(title)
        _apply_axis_scale_and_range(ax, axis_info, axis="x")

    for axis_id, axis_info in subplot_info["yaxes"].items():
        row = subplot_info["y_to_row"].get(axis_id, 0)
        col = _col_for_yaxis(subplot_info, axis_id)
        ax = axes[row, col]
        title = _get_title_text(axis_info.get("title"))
        if title:
            ax.set_ylabel(title)
        _apply_axis_scale_and_range(ax, axis_info, axis="y")

    for index, annotation in enumerate(annotations):
        annotation = _to_plain_dict(annotation)
        text = annotation.get("text")
        if not text:
            continue
        if index >= axes.size:
            continue
        row, col = divmod(index, axes.shape[1])
        axes[row, col].set_title(text)


def _row_for_xaxis(subplot_info: dict[str, Any], xaxis: str) -> int:
    for (x_id, _), (row, _) in subplot_info["trace_axes"].items():
        if x_id == xaxis:
            return row
    return 0


def _col_for_yaxis(subplot_info: dict[str, Any], yaxis: str) -> int:
    for (_, y_id), (_, col) in subplot_info["trace_axes"].items():
        if y_id == yaxis:
            return col
    return 0


def _get_title_text(title: Any) -> str | None:
    if title is None:
        return None
    if isinstance(title, str):
        return title
    title = _to_plain_dict(title)
    return title.get("text")


def _apply_axis_scale_and_range(ax: Any, axis_info: dict[str, Any], *, axis: str) -> None:
    if axis_info.get("type") == "log":
        getattr(ax, f"set_{axis}scale")("log")

    axis_range = axis_info.get("range")
    if axis_range is not None and len(axis_range) >= 2:
        setter = ax.set_xlim if axis == "x" else ax.set_ylim
        setter(axis_range[0], axis_range[1])


def _get_axis_for_trace(
    axes: np.ndarray,
    subplot_info: dict[str, Any],
    trace: dict[str, Any],
) -> Any:
    key = (trace.get("xaxis", "x"), trace.get("yaxis", "y"))
    row, col = subplot_info["trace_axes"].get(key, (0, 0))
    return axes[row, col]


def _draw_trace(
    ax: Any,
    trace: dict[str, Any],
    *,
    include_colorbar: bool,
    mpl_fig: Any,
) -> None:
    trace_type = trace.get("type", "scatter")
    if trace_type in {"scatter", "scattergl"}:
        _draw_scatter(ax, trace, include_colorbar=include_colorbar, mpl_fig=mpl_fig)
    elif trace_type == "histogram":
        _draw_histogram(ax, trace)
    elif trace_type == "heatmap":
        _draw_heatmap(ax, trace, include_colorbar=include_colorbar, mpl_fig=mpl_fig)
    elif trace_type == "bar":
        _draw_bar(ax, trace)
    else:
        raise NotImplementedError(f"Unsupported Plotly trace type: {trace_type}")


def _draw_scatter(
    ax: Any,
    trace: dict[str, Any],
    *,
    include_colorbar: bool,
    mpl_fig: Any,
) -> None:
    y = _array_or_none(trace.get("y"))
    if y is None:
        return
    x = _array_or_none(trace.get("x"))
    if x is None:
        x = np.arange(len(y))

    mode = trace.get("mode", "markers")
    marker = _to_plain_dict(trace.get("marker", {}))
    line = _to_plain_dict(trace.get("line", {}))
    label = trace.get("name")
    marker_color = marker.get("color")
    line_color = line.get("color") or marker_color
    marker_symbol = _plotly_marker_to_matplotlib(marker.get("symbol"))
    marker_size = marker.get("size", 6)
    opacity = marker.get("opacity", trace.get("opacity", 1.0))
    line_width = line.get("width", 1)
    line_style = _plotly_dash_to_matplotlib(line.get("dash"))

    has_lines = "lines" in mode
    has_markers = "markers" in mode
    has_text = "text" in mode
    color_values = _numeric_array_or_none(marker_color)
    cmap = _colorscale_to_cmap(marker.get("colorscale"))

    xerr = _error_to_matplotlib(trace.get("error_x"), x)
    yerr = _error_to_matplotlib(trace.get("error_y"), y)

    if has_lines:
        ax.plot(
            x,
            y,
            color=_scalar_color(line_color),
            linewidth=line_width,
            linestyle=line_style,
            label=label if not has_markers and xerr is None and yerr is None else None,
        )

    if xerr is not None or yerr is not None:
        ax.errorbar(
            x,
            y,
            xerr=xerr,
            yerr=yerr,
            fmt=_errorbar_fmt(has_markers, marker_symbol),
            color=_scalar_color(line_color),
            ecolor=_scalar_color(line_color),
            markersize=float(marker_size),
            linewidth=line_width if has_lines else 0,
            elinewidth=line_width,
            capsize=_errorbar_capsize(trace),
            linestyle=line_style if has_lines else "none",
            alpha=opacity,
            label=label,
        )
    elif has_markers:
        if color_values is not None:
            artist = ax.scatter(
                x,
                y,
                c=color_values,
                cmap=cmap,
                marker=marker_symbol,
                s=float(marker_size) ** 2,
                alpha=opacity,
                label=label,
            )
            if include_colorbar:
                colorbar = mpl_fig.colorbar(artist, ax=ax)
                _apply_colorbar_title(colorbar, marker.get("colorbar"))
        else:
            ax.scatter(
                x,
                y,
                color=_scalar_color(marker_color),
                marker=marker_symbol,
                s=float(marker_size) ** 2,
                alpha=opacity,
                label=label,
            )

    if has_text:
        text_values = trace.get("text", [])
        if isinstance(text_values, str):
            text_values = [text_values] * len(x)
        for xi, yi, text in zip(x, y, text_values):
            ax.text(xi, yi, str(text))


def _draw_histogram(ax: Any, trace: dict[str, Any]) -> None:
    x = _array_or_none(trace.get("x"))
    if x is None:
        return

    marker = _to_plain_dict(trace.get("marker", {}))
    xbins = _to_plain_dict(trace.get("xbins", {}))
    bins: int | np.ndarray | None = trace.get("nbinsx")

    if {"start", "end", "size"} <= xbins.keys():
        start = float(xbins["start"])
        end = float(xbins["end"])
        size = float(xbins["size"])
        bins = np.arange(start, end + size, size)

    ax.hist(
        x,
        bins=bins,
        color=_scalar_color(marker.get("color")),
        alpha=trace.get("opacity", marker.get("opacity", 1.0)),
        label=trace.get("name"),
    )


def _draw_heatmap(
    ax: Any,
    trace: dict[str, Any],
    *,
    include_colorbar: bool,
    mpl_fig: Any,
) -> None:
    z = _array_or_none(trace.get("z"))
    if z is None:
        return

    x = _array_or_none(trace.get("x"))
    y = _array_or_none(trace.get("y"))
    if x is None:
        x = np.arange(z.shape[1])
    if y is None:
        y = np.arange(z.shape[0])

    x_edges = _centers_to_edges(x)
    y_edges = _centers_to_edges(y)
    cmap = _colorscale_to_cmap(trace.get("colorscale"))

    artist = ax.pcolormesh(
        x_edges,
        y_edges,
        z,
        cmap=cmap,
        vmin=trace.get("zmin"),
        vmax=trace.get("zmax"),
        shading="auto",
    )

    if include_colorbar:
        colorbar = mpl_fig.colorbar(artist, ax=ax)
        _apply_colorbar_title(colorbar, trace.get("colorbar"))


def _draw_bar(ax: Any, trace: dict[str, Any]) -> None:
    y = _array_or_none(trace.get("y"))
    if y is None:
        return
    x = _array_or_none(trace.get("x"))
    if x is None:
        x = np.arange(len(y))
    marker = _to_plain_dict(trace.get("marker", {}))

    ax.bar(
        x,
        y,
        color=_scalar_color(marker.get("color")),
        alpha=trace.get("opacity", marker.get("opacity", 1.0)),
        width=trace.get("width", 0.8),
        label=trace.get("name"),
    )


def _array_or_none(value: Any) -> np.ndarray | None:
    if value is None:
        return None
    value = _decode_typed_array(value)
    return np.asarray(value)


def _numeric_array_or_none(value: Any) -> np.ndarray | None:
    if value is None or isinstance(value, str):
        return None
    value = _decode_typed_array(value)
    if not isinstance(value, Iterable):
        return None
    array = np.asarray(value)
    return array if np.issubdtype(array.dtype, np.number) else None


def _decode_typed_array(value: Any) -> Any:
    if not isinstance(value, dict):
        return value
    if "dtype" not in value or "bdata" not in value:
        return value

    dtype = np.dtype(value["dtype"])
    raw = base64.b64decode(value["bdata"])
    array = np.frombuffer(raw, dtype=dtype)
    shape = value.get("shape")
    if shape:
        if isinstance(shape, str):
            shape = tuple(int(s) for s in shape.split(","))
        array = array.reshape(shape)
    return array


def _scalar_color(color: Any) -> Any:
    if color is None:
        return None
    if isinstance(color, str):
        return color
    return None


def _plotly_marker_to_matplotlib(symbol: Any) -> str:
    if symbol is None:
        return "o"
    symbol = str(symbol).replace("-open", "").replace("-dot", "")
    return {
        "circle": "o",
        "square": "s",
        "diamond": "D",
        "cross": "x",
        "x": "x",
        "triangle-up": "^",
        "triangle-down": "v",
        "triangle-left": "<",
        "triangle-right": ">",
        "star": "*",
        "hexagon": "h",
        "pentagon": "p",
        "plus": "+",
    }.get(symbol, "o")


def _plotly_dash_to_matplotlib(dash: Any) -> str:
    return {
        None: "-",
        "solid": "-",
        "dash": "--",
        "dot": ":",
        "dashdot": "-.",
        "longdash": "--",
        "longdashdot": "-.",
    }.get(dash, "-")


def _errorbar_fmt(has_markers: bool, marker_symbol: str) -> str:
    return marker_symbol if has_markers else "none"


def _errorbar_capsize(trace: dict[str, Any]) -> float:
    values = []
    for key in ("error_x", "error_y"):
        error = trace.get(key)
        if error is not None:
            values.append(_to_plain_dict(error).get("width", 0))
    return float(max(values) if values else 0)


def _error_to_matplotlib(error: Any, base: np.ndarray) -> Any:
    if error is None:
        return None
    error = _to_plain_dict(error)
    if error.get("visible") is False:
        return None

    array = error.get("array")
    if array is None:
        value = error.get("value")
        if value is None:
            return None
        array = np.full_like(base, value, dtype=float)
    else:
        array = np.asarray(_decode_typed_array(array), dtype=float)

    if error.get("type") == "percent":
        array = np.asarray(base, dtype=float) * array / 100.0

    arrayminus = error.get("arrayminus")
    if arrayminus is None:
        return array

    arrayminus = np.asarray(_decode_typed_array(arrayminus), dtype=float)
    if error.get("type") == "percent":
        arrayminus = np.asarray(base, dtype=float) * arrayminus / 100.0
    return np.vstack([arrayminus, array])


def _centers_to_edges(values: np.ndarray) -> np.ndarray:
    values = np.asarray(values, dtype=float)
    if len(values) == 0:
        return values
    if len(values) == 1:
        return np.array([values[0] - 0.5, values[0] + 0.5])

    mids = (values[:-1] + values[1:]) / 2.0
    first = values[0] - (mids[0] - values[0])
    last = values[-1] + (values[-1] - mids[-1])
    return np.concatenate([[first], mids, [last]])


def _colorscale_to_cmap(colorscale: Any):
    plt, LinearSegmentedColormap = _import_matplotlib()
    if colorscale is None:
        return plt.get_cmap("viridis")

    if isinstance(colorscale, str):
        cmap_name = colorscale.lower()
        aliases = {
            "turbo": "turbo",
            "viridis": "viridis",
            "plasma": "plasma",
            "inferno": "inferno",
            "magma": "magma",
            "cividis": "cividis",
            "gray": "gray",
            "greys": "gray",
        }
        try:
            return plt.get_cmap(aliases.get(cmap_name, cmap_name))
        except ValueError:
            return plt.get_cmap("viridis")

    if isinstance(colorscale, list):
        colors = []
        for item in colorscale:
            if isinstance(item, (list, tuple)) and len(item) >= 2:
                colors.append((float(item[0]), _plotly_color_to_mpl(item[1])))
        if colors:
            return LinearSegmentedColormap.from_list("plotly_colorscale", colors)

    return plt.get_cmap("viridis")


def _plotly_color_to_mpl(color: Any) -> Any:
    if not isinstance(color, str):
        return color
    color = color.strip()
    if color.startswith("rgb(") and color.endswith(")"):
        values = color[4:-1].split(",")
        return tuple(float(value.strip()) / 255.0 for value in values[:3])
    if color.startswith("rgba(") and color.endswith(")"):
        values = color[5:-1].split(",")
        rgb = [float(value.strip()) / 255.0 for value in values[:3]]
        alpha = float(values[3].strip())
        return (*rgb, alpha)
    return color


def _apply_colorbar_title(colorbar: Any, colorbar_info: Any) -> None:
    if colorbar_info is None:
        return
    colorbar_info = _to_plain_dict(colorbar_info)
    title = _get_title_text(colorbar_info.get("title"))
    if title:
        colorbar.set_label(title)


def _apply_legends(
    axes: np.ndarray,
    layout: dict[str, Any],
    showlegend: bool | None,
) -> None:
    if showlegend is None:
        showlegend = bool(layout.get("showlegend", False))
    if not showlegend:
        return

    for ax in axes.flat:
        handles, labels = ax.get_legend_handles_labels()
        labels = [label for label in labels if label and not label.startswith("_")]
        if handles and labels:
            ax.legend()


def _hide_empty_axes(axes: np.ndarray) -> None:
    for ax in axes.flat:
        if not ax.has_data():
            ax.set_visible(False)
