[project]
name = "marimo-lib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "FumiHubCNS", email = "fendo@cns.s.u-tokyo.ac.jp" }
]
requires-python = ">=3.10"
dependencies = [
    "anywidget>=0.9.21",
    "json5>=0.12.1",
    "marimo>=0.23.3",
    "mohtml>=0.1.11",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "plotly>=6.4.0",
    "pyzmq>=27.1.0",
    "scipy>=1.15.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.marimo.runtime]
output_max_bytes = 50_000_000

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.1",
    "pdoc>=16.0.0",
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
mkdocs = """ mkdir -p page/docs/examples && rm -rf page/docs/examples/* && cp -R notebook/__marimo__/* page/docs/examples/ && mkdocs build -v -f page/mkdocs.yml"""
pdoc = """rm -rf docs/marimo-lib && pdoc marimo_lib.util marimo_lib.analysis --output-directory docs/marimo-lib --math --docformat google"""
